// Package memory — scene.go: L2 thematic scene management.
//
// A "scene" is a small (≤15 per persona) thematic block that groups related
// L1 atoms. Each scene has a title, a one-line summary (injected into the
// system prompt as part of the persona's table-of-contents), and a markdown
// body where the LLM can elaborate.
//
// # Why a hard cap of 15?
//
// Two reasons:
//
//   - System-prompt budget: each scene contributes ~30 tokens to the
//     header. 15 × 30 ≈ 450 tokens is the most we want to "spend" before
//     the prompt feels bloated.
//   - Forces consolidation: the LLM cannot keep creating new scenes
//     forever, which is what makes the memory pyramid actually pyramid-
//     shaped (instead of a flat bag of facts).
//
// When the persona is at capacity, the scene-fitter prompt is forced into
// merge-mode: it MUST collapse two existing scenes (and re-tag their atoms)
// before adding a new one.

package memory

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"gorm.io/gorm"

	"github.com/opentheone/opentheone/backend/internal/llm"
	"github.com/opentheone/opentheone/backend/internal/model"
)

// MaxScenesPerPersona is the upper bound on a persona's L2 scene count.
// See package doc for rationale. 15 was the user-confirmed default.
const MaxScenesPerPersona = 15

// SceneFitDecision is one LLM-emitted routing instruction for an atom.
type SceneFitDecision struct {
	AtomID     string `json:"atom_id"`
	Action     string `json:"action"`   // "fit" | "create" | "merge_then_create"
	SceneID    string `json:"scene_id"` // present for "fit"
	NewTitle   string `json:"new_title"`
	NewSummary string `json:"new_summary"`
	// MergeFrom is the scene IDs the LLM wants to merge BEFORE creating the
	// new one (used when we're at capacity). The merged scene's title /
	// summary will be regenerated by a follow-up scene_compose call.
	MergeFrom []string `json:"merge_from"`
}

// FitAtomsToScenes places freshly created atoms into L2 scenes via a single
// LLM call.
//
// The decision protocol is intentionally narrow: per atom the LLM may
//   - fit              attach to an existing scene
//   - create           start a new scene (only allowed below the cap)
//   - merge_then_create collapse two scenes, then create (only at the cap)
//
// Returns the set of scene_ids that were touched (created or modified) so
// the caller can trigger a follow-up scene-compose pass if needed.
func (s *Service) FitAtomsToScenes(ctx context.Context, client *llm.Client, personaID string, atomIDs []string) ([]string, error) {
	if len(atomIDs) == 0 {
		return nil, nil
	}
	if client == nil {
		// Without an LLM we can't classify; leave atoms scene-less. The
		// next time the pipeline runs with a real client they'll get
		// picked up.
		return nil, nil
	}

	var atoms []model.Memory
	if err := s.db.WithContext(ctx).
		Where("id IN ? AND status = ?", atomIDs, "active").
		Find(&atoms).Error; err != nil {
		return nil, err
	}
	if len(atoms) == 0 {
		return nil, nil
	}

	var existing []model.MemoryScene
	if err := s.db.WithContext(ctx).
		Where("persona_id = ?", personaID).
		Order("heat desc, updated_at desc").
		Find(&existing).Error; err != nil {
		return nil, err
	}
	atCap := len(existing) >= MaxScenesPerPersona

	var b strings.Builder
	b.WriteString("【现有场景】（按热度排序）\n")
	if len(existing) == 0 {
		b.WriteString("（空）\n")
	}
	for _, sc := range existing {
		fmt.Fprintf(&b, "[%s] %s — %s\n", sc.ID, sc.Title, oneLine(sc.Summary))
	}
	b.WriteString("\n【需要归类的新原子记忆】\n")
	for _, a := range atoms {
		fmt.Fprintf(&b, "[%s | kind=%s] %s\n", a.ID, a.Kind, strings.TrimSpace(a.Content))
	}
	fmt.Fprintf(&b, "\n【约束】当前场景数 = %d / 上限 = %d。", len(existing), MaxScenesPerPersona)
	if atCap {
		b.WriteString(" 已达上限，create 必须先 merge_from 至少 2 个旧场景！")
	}
	b.WriteString("\n请按要求输出 JSON。")

	msgs := []llm.ChatMessage{
		{Role: "system", Content: sceneFitterSystemPrompt},
		{Role: "user", Content: b.String()},
	}
	raw, err := client.Chat(ctx, msgs)
	if err != nil {
		return nil, fmt.Errorf("memory.FitAtomsToScenes: chat: %w", err)
	}
	raw = stripJSONFence(raw)
	var out struct {
		Decisions []SceneFitDecision `json:"decisions"`
	}
	if err := json.Unmarshal([]byte(raw), &out); err != nil {
		return nil, fmt.Errorf("memory.FitAtomsToScenes: parse json: %w (raw=%q)", err, raw)
	}

	now := time.Now()
	touched := map[string]bool{}

	err = s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, d := range out.Decisions {
			d.Action = strings.ToLower(strings.TrimSpace(d.Action))
			switch d.Action {
			case "fit":
				if d.SceneID == "" {
					continue
				}
				if err := tx.Model(&model.Memory{}).
					Where("id = ?", d.AtomID).
					Update("scene_id", d.SceneID).Error; err != nil {
					return err
				}
				if err := tx.Model(&model.MemoryScene{}).
					Where("id = ?", d.SceneID).
					Updates(map[string]interface{}{
						"atom_count":   gorm.Expr("atom_count + 1"),
						"last_atom_at": now,
					}).Error; err != nil {
					return err
				}
				touched[d.SceneID] = true
			case "create":
				// Hard-reject create when we're already at cap — the
				// prompt told the LLM to merge_then_create in that case;
				// honoring an obstinate `create` would silently push us
				// past MaxScenesPerPersona and dilute the index. We count
				// scenes inside the tx so concurrent writers can't sneak
				// past the cap. The atom stays orphan (scene_id="") and
				// the next pipeline tick's orphan-rescue path will pick
				// it up — by then a real scene may exist for it.
				var n int64
				if err := tx.Model(&model.MemoryScene{}).
					Where("persona_id = ?", personaID).
					Count(&n).Error; err != nil {
					return err
				}
				if int(n) >= MaxScenesPerPersona {
					continue
				}
				newSceneID, err := createScene(tx, personaID, d.NewTitle, d.NewSummary, now)
				if err != nil {
					return err
				}
				if err := tx.Model(&model.Memory{}).
					Where("id = ?", d.AtomID).
					Update("scene_id", newSceneID).Error; err != nil {
					return err
				}
				touched[newSceneID] = true
			case "merge_then_create":
				if len(d.MergeFrom) < 2 {
					// Bad model output — refuse to create-only when we're
					// at cap (would violate MaxScenesPerPersona). Skip
					// this decision; orphan-rescue will retry the atom
					// next tick.
					var n int64
					if err := tx.Model(&model.MemoryScene{}).
						Where("persona_id = ?", personaID).
						Count(&n).Error; err != nil {
						return err
					}
					if int(n) >= MaxScenesPerPersona {
						continue
					}
				} else if err := mergeScenes(tx, personaID, d.MergeFrom, now); err != nil {
					return err
				}
				newSceneID, err := createScene(tx, personaID, d.NewTitle, d.NewSummary, now)
				if err != nil {
					return err
				}
				if err := tx.Model(&model.Memory{}).
					Where("id = ?", d.AtomID).
					Update("scene_id", newSceneID).Error; err != nil {
					return err
				}
				touched[newSceneID] = true
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	ids := make([]string, 0, len(touched))
	for id := range touched {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids, nil
}

// ListScenes returns all scenes for a persona, sorted heat desc.
func (s *Service) ListScenes(ctx context.Context, personaID string) ([]model.MemoryScene, error) {
	var out []model.MemoryScene
	err := s.db.WithContext(ctx).
		Where("persona_id = ?", personaID).
		Order("heat desc, updated_at desc").
		Find(&out).Error
	return out, err
}

// GetScene returns one scene plus its currently-active atoms.
func (s *Service) GetScene(ctx context.Context, personaID, sceneID string) (*model.MemoryScene, []model.Memory, error) {
	var sc model.MemoryScene
	if err := s.db.WithContext(ctx).
		Where("id = ? AND persona_id = ?", sceneID, personaID).
		First(&sc).Error; err != nil {
		return nil, nil, err
	}
	var atoms []model.Memory
	if err := s.db.WithContext(ctx).
		Where("scene_id = ? AND status = ?", sceneID, "active").
		Order("importance desc, created_at desc").
		Find(&atoms).Error; err != nil {
		return nil, nil, err
	}
	// Heat counter: reading a scene is a signal of relevance.
	_ = s.db.WithContext(ctx).Model(&model.MemoryScene{}).
		Where("id = ?", sceneID).
		Update("heat", gorm.Expr("heat + 1")).Error
	return &sc, atoms, nil
}

// DeleteScene drops a scene and clears the scene_id on its atoms (the atoms
// themselves survive — only the grouping is removed, so a future scene-fit
// pass can re-route them).
func (s *Service) DeleteScene(ctx context.Context, personaID, sceneID string) error {
	return s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var sc model.MemoryScene
		if err := tx.Where("id = ? AND persona_id = ?", sceneID, personaID).First(&sc).Error; err != nil {
			return err
		}
		if err := tx.Model(&model.Memory{}).
			Where("scene_id = ?", sceneID).
			Update("scene_id", "").Error; err != nil {
			return err
		}
		return tx.Delete(&sc).Error
	})
}

// SceneIndexForPrompt formats up to N most-relevant scenes for injection
// into the system prompt header (the "table of contents" the model uses to
// decide whether to call scene_read for details).
//
// Output looks like:
//
//	【你记忆中的主题场景索引】
//	1. AI 和猫猫聊咖啡习惯 — 关注手冲器材、起床时间
//	2. 工作进展 — 6 月初要交付 OTO MVP
//	…
//
// Returns empty string when the persona has no scenes yet.
func (s *Service) SceneIndexForPrompt(ctx context.Context, personaID string, limit int) (string, error) {
	if limit <= 0 || limit > MaxScenesPerPersona {
		limit = MaxScenesPerPersona
	}
	var scs []model.MemoryScene
	if err := s.db.WithContext(ctx).
		Where("persona_id = ?", personaID).
		Order("heat desc, updated_at desc").
		Limit(limit).Find(&scs).Error; err != nil {
		return "", err
	}
	if len(scs) == 0 {
		return "", nil
	}
	var b strings.Builder
	b.WriteString("【你记忆中的主题场景索引】（需要细节时用 scene_read 工具查阅）\n")
	for i, sc := range scs {
		fmt.Fprintf(&b, "%d. %s — %s\n", i+1, sc.Title, oneLine(sc.Summary))
	}
	return b.String(), nil
}

func createScene(tx *gorm.DB, personaID, title, summary string, now time.Time) (string, error) {
	title = strings.TrimSpace(title)
	if title == "" {
		title = "新场景"
	}
	sc := model.MemoryScene{
		PersonaID:  personaID,
		Title:      title,
		Summary:    strings.TrimSpace(summary),
		AtomCount:  1,
		LastAtomAt: &now,
	}
	if err := tx.Create(&sc).Error; err != nil {
		return "", err
	}
	return sc.ID, nil
}

// mergeScenes folds the named scenes into a single placeholder scene named
// "（合并中：旧场景 N 个）" — the next pipeline tick will run scene-compose
// to rewrite title+summary properly. We do it this way (placeholder first,
// rewrite later) so the merge can complete inside the current transaction
// without an extra LLM round-trip.
func mergeScenes(tx *gorm.DB, personaID string, sceneIDs []string, now time.Time) error {
	if len(sceneIDs) < 2 {
		return errors.New("memory.mergeScenes: need at least 2 scenes")
	}
	placeholder := model.MemoryScene{
		PersonaID:  personaID,
		Title:      "（合并中）",
		Summary:    "下一轮 pipeline 会重写标题",
		AtomCount:  0,
		LastAtomAt: &now,
	}
	if err := tx.Create(&placeholder).Error; err != nil {
		return err
	}
	// Re-tag atoms.
	res := tx.Model(&model.Memory{}).
		Where("persona_id = ? AND scene_id IN ?", personaID, sceneIDs).
		Update("scene_id", placeholder.ID)
	if res.Error != nil {
		return res.Error
	}
	if err := tx.Model(&placeholder).
		Update("atom_count", res.RowsAffected).Error; err != nil {
		return err
	}
	// Drop the old scenes.
	return tx.Where("id IN ?", sceneIDs).Delete(&model.MemoryScene{}).Error
}

// oneLine flattens multi-line summaries to a single line for the prompt
// index (we keep raw scenes multi-line in the DB so users can read them
// from the management UI).
func oneLine(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "（待生成）"
	}
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	if r := []rune(s); len(r) > 60 {
		s = string(r[:60]) + "…"
	}
	return s
}

const sceneFitterSystemPrompt = `你是 OpenTheOne 的「L2 场景归类器」。
你的任务是把一批新增的「原子记忆」分配到合适的「主题场景」中。

【输出格式】严格输出 JSON：
{
  "decisions": [
    {
      "atom_id":    "atom 的 uuid",
      "action":     "fit | create | merge_then_create",
      "scene_id":   "（仅 fit）已有场景 uuid",
      "new_title":  "（create 或 merge_then_create）新场景标题，≤16字",
      "new_summary":"（create 或 merge_then_create）一句话场景说明，≤40字",
      "merge_from": ["（仅 merge_then_create）要合并的至少 2 个旧场景 uuid"]
    }
  ]
}

【场景命名规范】
- 标题必须用「AI 在和用户做什么」的主动叙述。例：「AI 和用户聊咖啡」「AI 在帮用户排周末计划」。
- 不要使用名词短语（坏例：「咖啡话题」「周末计划」）。
- 不要含具体日期，让场景能跨多个时间点复用。

【动作判定原则】
1. 若 atom 明显属于某个已有场景的主题 → fit。
2. 若 atom 是全新主题且场景数未达上限 → create。
3. 若 atom 是全新主题但场景数已达上限 → merge_then_create，并指定 2 个语义最接近的旧场景进行合并。
4. 一组 atom 可以分别归到不同场景，但同一组里只允许出现一次 create（或 merge_then_create）。
5. 不要为了归类而生硬塞进不相关的场景；宁可 create 一个新场景。
6. 不要输出 JSON 以外的内容。`
